apiVersion: v2
description: Deploy Kong Ingress Controller and Kong Gateway
home: https://konghq.com/
icon: https://s3.amazonaws.com/downloads.kong/universe/assets/icon-kong-inc-large.png
maintainers:
  - name: team-k8s-bot
    email: team-k8s@konghq.com
name: ingress
sources:
  - https://github.com/ProvLabs/kong-helm-charts/tree/scirner22/additional-listener-config/charts/ingress
version: 0.19.0
appVersion: "3.9"
dependencies:
  - name: kong
    version: "=2.48.0"
    repository: 'file://../../charts/kong'
    alias: controller
    condition: controller.enabled
  - name: kong
    version: "=2.48.0"
    repository: 'file://../../charts/kong'
    alias: gateway
    condition: gateway.enabled
